### ISSUE TITLE
Consider more proactive sanitizing of inputs and output in API

### ISSUE THREAD

**Issue by kltm** [geneontology/biolink-api#12]
From https://github.com/geneontology/biolink-api/issues/11, it looks like some bot was doing some gentle probing of the API using SQL injection to try and find a way in. It naturally didn't do much as there is no SQL backend, etc. (at this point anyways), but it does highlight something that can become problematic. As well, it triggered a firewall bot to (correctly IMO) block the source, which unfortunately broke an application.

I would suggest that it might be good to consider a more proactive stance to prevent misunderstandings like this from propagating. Basic input sanity checks (from one of the many libraries that do this) might help prevent future issues from cropping up.

From #11:
```
-> "and 1=1&rows=1000" 

http://131.243.192.30/solr/select?q=*:*&qf=&fq=document_category:\"ontology_class\"&fl=annotation_class,annotation_class_label,description,source&wt=json&indent=on&fq=subset:goslim_agr and 1=1&rows=1000

1=1 is likely what triggered the sql injection attack! 
```

**Comment by lpalbou** [comment]
This needs clarification about what sanity checks you would want. Also, things to consider:

* adding sanity checks to the GO API doesn't protect GOLr as GOLr is publicly accessible from the internet and is the actual target of those attacks. What you propose makes sense in an architecture where the database is private and only accessible through an API, but this is not the case here and the same query/attack can be sent directly to GOLr without the GO API, so I am unsure what we would gain with your proposal

* the GO API is for the moment a fork of the biolink API. Any update on security would probably gained to be done at the level of the biolink parent repo rather than here

* in addition and as described here https://github.com/geneontology/biolink-api/issues/11#issuecomment-794788906, the GO API has no write capability, and it only accesses a read only instance of GOLr which doesn't contain any private data. In the event an attack succeeds, at worst they would retrieve publicly available data or crash GOLr (which should autorelaunch, like the GO API does). If you are concerned about golr-aux being on the LBL network, I can add a script to launch a private GOLr instance at each GO release, and that private instance (unreachable by internet) would be the target of the GO API. This would actually makes the API faster and more scalable and was discussed in the past and in https://github.com/geneontology/biolink-api/issues/7

* the GO API is due for a refactoring. This was discussed with @cmungall but I don't know where we stand in terms of priority

For all these reasons, I don't think this should be done. The main point here is that GOLr (and not the GO API) is the target of potential attacks but since GOLr is publicly accessible, adding protections to the GO API doesn't protect GOLr at all.. In addition, there are other parts of the architecture that are IMO much more concerning and having a group discussion about security & how to prioritize it could be helpful.

**Comment by kltm** [comment]
@lpalbou Whoops, yeah--I totally missed the repo!
