### ISSUE TITLE
support both https and http on the landing page (currently swagger and the link on the landing page show localhost and fail respectively).

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/biolink-api#32]

**Comment by sierra-moxon** [comment]
https://github.com/geneontology/biolink-api/blob/master/biolink/app.py
base_url is set here.

**Comment by sierra-moxon** [comment]
from 2/22/23 meeting with Seth: remove the splash page, no longer needed.

**Comment by kltm** [comment]
To specify more if somebody comes back to this:
1. it's use case was unclear
2. it sometimes caused people to believe it was an error message (rather than a landing page)
3. the code for it was nice to get cleaned out as it was a smoother fit without
4. it has some confusing linking issues when interacting with an upstream HTTPS proxy
